### ISSUE TITLE
Doesn't seem to work on 10.13.4

### ISSUE THREAD

**Issue by lozzd** [iccir/Fermata#1]
Hi!
Is it expected this utility will still work on 10.13.X? I'm running 10.13.4, and even if I manually select the menu option to disable lid close sleep, the laptop sleeps when I close the lid. 

Thanks!

**Comment by iccir** [comment]
It should, but I noticed that 10.13.4 isn't working on my laptop. I'll try to investigate today!

**Comment by iccir** [comment]
Apple restricted the `AppliesOnLidClose` property to applications which have a private `com.apple.private.iokit.assertonlidclose` entitlement. There's not much that I can do to get around this.

**Comment by lozzd** [comment]
Why oh why must Apple ruin things for everyone? 😄 

I've resorted to using a shell script that just runs a `sudo pmset -b disablesleep 1; sudo pmset -b sleep 0` and restores it <timeout> period later, so if I move the laptop to another meeting room, I run it and it will keep it awake for (default) 300 seconds then restore the previous Sleep config. 

It sucks to shell out to such commands, but maybe could reimplement it using that? You may consider that outside of the scope of your original tool though.

**Comment by iccir** [comment]
I'm still investigating, but it looks like the only solution is to use a kernel extension. In theory, if I can get a kext signing certificate from Apple (which is probably unlikely), a user would be able to [opt-in to the kext](https://developer.apple.com/library/content/technotes/tn2459/_index.html) without disabling System Integrity Protection. I've sent a request to Apple.

**Comment by iccir** [comment]
It… appears to work! Well, now I know what my project tomorrow is ;) Thanks!

I'm nocturnal, and I'm about to go to bed, but hopefully I'll have something in 24 hours (unless another crisis hits!)

**Comment by lozzd** [comment]
Ha! While I'm here, it would also be great if you could have a default timer so you couldn't forget to turn it off (if not using it with the app option). Might be a separate issue though :)

**Comment by iccir** [comment]
Please file a separate issue and elaborate a bit on your exact use case (if possible). I do worry about users accidentally leaving it on and tossing it in their laptop bag - I'm still not sure the best way to address this.

And thanks for the report!

**Comment by iccir** [comment]
Can you test out https://github.com/iccir/Fermata/releases/tag/126 ? Thanks!

**Comment by lozzd** [comment]
It works! Awesome! Thanks!

**Comment by iccir** [comment]
I think this is safe to close now :) Thanks again for the report!
