### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by jcphlux** [iccir/Fermata#3]
How do I install?

**Comment by iccir** [comment]
From the [Releases](https://github.com/iccir/Fermata/releases) tab, download the latest ("Fermata-128.zip"), extract, and run the app.

**Comment by slhck** [comment]
I had the same issue – I was expecting some “Installation” guide in the README. Would it be possible to add a sentence or two?

**Comment by iccir** [comment]
Good idea! Modified the README to point to the releases tab. Thanks!
